/**
 * 
 */
package com.Project.PlantDiagno;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;

/**
 * @author hp
 *
 */

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class InscriptionControleur {
	
	   @Autowired // This means to get the bean called userRepository
    			// Which is auto-generated by Spring, we will use it to handle the data
		private UserRepository userRepository;
	   
	   
	   
	   @GetMapping(path="/add") // Map ONLY POST Requests
	   public @ResponseBody String addNewUser (@RequestParam String username
	       , @RequestParam String email) {
	     // @ResponseBody means the returned String is the response, not a view name
	     // @RequestParam means it is a parameter from the GET or POST request

	     User u1 = new User();
	     u1.setUsername(username);
	     u1.setEmail(email);
	     userRepository.save(u1);
	     return "authentification"; //afficher l'authentification avec un message ok
	   }
}
